### ISSUE TITLE
Fonts link and required fonts other than Plex

### ISSUE THREAD

**Issue by jydesign** [carbon-design-system/carbon-design-kit#34]
Hi, in the designers section:
"The Carbon Design Kit now uses the new typeface IBM Plex. It is open sourced and free to download from the IBM GitHub repo"

The link to download Plex appears to be incorrect, I was able to find here instead: https://github.com/IBM/plex/releases

Also, when opening the Sketch library, it not only requires Plex, but I'm getting a missing font error on 'Helvetica Neue Bold IBM" that does not appear to be part of the Plex typeface library.
<img width="482" alt="screen shot 2018-03-02 at 9 06 04 am" src="https://user-images.githubusercontent.com/7850763/36902795-bd5802fa-1df9-11e8-8b04-05428ac94110.png">

regards J.

**Comment by tay-aitken** [comment]
Hey @jydesign thanks for pointing out these errors! We will make sure to update the link. As for the instance of Helvetica it could be one of two things:

1. We realized after we released the kit that the data vis page in the kit had somehow reverted to Helvetica through text styles; it should have been set in Plex. If your Data Vis page is still set in Helvetica then I would suggest re-downloading the kit. We fixed it after we realized our error on release day and re-released the kit. 

2. If your Data Vis page is set to Plex than that means there is a small instance of Helvetica somewhere that we need to find and replace/remove. If this is the case, do not worry about downloading Helvetica, Plex is the only font you need. We will make sure to remove that use of Helvetica for the next kit release. 

Let me know if either of these scenarios apply so I know what issue needs to be fixed. Thanks 😀

**Comment by aagonzales** [comment]
Thanks for making the issue. I believe this issues have been solved.

**Comment by rauhala** [comment]
I still see this error after re-download of kit version 9.0.0. HelvNeue in `axis label` style in **Data Viz** page. There are also a lot of instances of Helvetica and HelvNeue in **Symbols** page. Those can be searched with Font Finder plugin. As an example, all texts in Titles-group are Helvetica Neue.

<img width="419" alt="screenshot 2018-10-06 at 10 44 14" src="https://user-images.githubusercontent.com/16488270/46568874-efa7fd80-c954-11e8-96dd-ed5f55d58184.png">

In addition to that, there are instances of Lucida Grande in **What's New** and **Style** -pages.
- What's new: All 2nd level bullets `-` seem to be Lucida Grande.
- Style: hex color definitions in `field-01` and `field-02` are Lucida Grande
